src/Interact.jl
Since `uuid4()` returns a `string`, we do not need to convert its return value to a string again.
=> No need to convert string to string

src/Interact.jl
`Pkg.installed` fails to detect IJulia provided through `LOAD_PATH`. And results in an exception when compared against the required version number.
This will prevent the exception and optimistically load `IJulia/setup.jl` (with a warning) when IJulia is detected but not its version.
It now loads `IJulia/setup.jl` even when it does find the IJulia version less than what is required, to keep the behavior uniform. But I'm not sure of the repercussions and am equally inclined to issue a different warning and disable it completely in this case.
=> allow working with IJulia loaded from LOAD_PATH

src/Interact.jl, src/widgets.jl
This implements #74, extending Base.parse but in a way that avoids ambiguity warnings. Alternatively, we could use a different name for this.
Also a few other things in separate commits. GtkInteract.jl (an unregistered package) expects `values` to be implemented, so I thought I'd throw that in here (I can move it to GtkInteract if you prefer). The last commit is the one that makes me most nervous about the absence of tests, esp. since my IJulia is tuned to 0.4.
=> Fix ambiguity warnings from Colors

src/widgets.jl
This fixes the following warning whenever ``html()`` is first used,
```julia
julia> using Interact
htm
julia> html("foo")
WARNING: both Interact and Base export "HTML"; uses of it in module Main must be qualified
Interact.HTML("","foo")
```
I don't think there's a value in keeping the export since it hasn't been usable on Julia 0.4 anyway
=> remove conflicting HTML export with Base

src/IJulia/handle_msg.jl, src/IJulia/setup.jl, src/Interact.jl, src/html_setup.jl
I think I was getting some problems with precompilation and js loading in IJulia (I was playing around with a module that had `using Interact` internally). I'm not 100% sure, but I think they were caused by the js not being loaded in an `__init__` function. Either way, afaict it seems sensible to load js in the `__init__` since it is affecting an external resource at runtime and not compile time, yeah? Or maybe I'm wrong and it's not needed as the js loading code is guaranteed to run at load time anyway after `using Interact` is called?
Anyway, even if it is a good idea, I'm still not 100% about this code being the best way to do it. I should note though that `Interact.__init__()` runs in `current_module() == Main` (or more accurately from whichever module `using Interact` is called from) …
=> Initialise JS in __init__ Function

deps/build.jl
Using an external Python3 interpreter instead of Py2 provided by Conda.jl, building `Interact.jl` fails with a syntax error due to `print` without parenthesis.
The `print()` syntax works for both Python 2 & 3.
=> Fixed print syntax for Python3.

src/manipulate.jl
Stops issues with manipulate signals being garbage collected when they go out of scope.
Fixes #115
=> Adds preserve to signal created by manipulate

src/IJulia/handle_msg.jl
It seems that the only reason Interact.jl can't display/print within `@manipulate`/`map` in IJulia (see #41), is just that IJulia is not sending the correct message header on stream messages and output/stream messages are being silently dropped by the front-end. This PR enables Interact to set the message header on stream messages.
Fixes (for the most part) #41
Requires a small change in IJulia, more details in the docstring of that PR: https://github.com/JuliaLang/IJulia.jl/pull/482
=> Enables output created during signal updates to be displayed by Jupyter

REQUIRE, src/IJulia/handle_msg.jl, src/IJulia/setup.jl, src/IJulia/statedict.jl, src/Interact.jl, src/widgets.jl, test/notebooks/Interact Manual Tests.ipynb
1. Adds SelectionSlider widget (`selection_slider`)
1. Adds SelectMultiple widget (`selectmulti`)
1. Renames `select` to `selectone` (to avoid name conflict with Base.select)
1. Enables vertical sliders (`orientation = "vertical"`)
1. Makes readout optional on sliders (`readout=false`)
1. Widget signals sync to the display of the widget better
1. Adds a notebook for manual testing
More info in the commit messages.
N.b. Each commit is mostly atomic, I could make multiple PRs if it suits you better. The first commit shown below is the Signal{Widget} one from #131
=> Various widget updates

src/widgets.jl, test/notebooks/Interact Manual Tests.ipynb
`set!(w::Widget, fld::Symbol, val)`
Set the value of a widget property and update all displayed instances of the
widget. If `val` is a `Signal`, then updates to that signal will be reflected in
widget instances/views.
If `fld` is `:value`, `val` is also `push!`ed to `signal(w)`
=> Adds `set!` function

src/IJulia/handle_msg.jl, src/IJulia/ijulia.js, src/IJulia/setup.jl, src/Interact.jl, src/widgets.jl, test/notebooks/Interact Manual Tests.ipynb
A few different fixes, see the commit messages for more details.
Also adds `vslider` and `vselection_slider`
I think it would be good to tag another release with these, the first commit is especially important since a `@manipulate` slider can behave weirdly without it - especially if the kernel is remote.
Commit 6 fixes #146 and the minor issue remaining in #144 (with the use of LaTeXStrings.jl)
=> A few fixes

.travis.yml, REQUIRE, src/Interact.jl
This turns on Travis builds for julia v0.5 and allows Travis to fail on v0.6 (in which there are currently IJulia build errors unrelated to this package). 
It also enables precompilation now that Reactive v0.3.7 has been tagged.
=> Fix travis build and enable precompilation

doc/dev guide.md
(markdown doesn't like lists without a blank line before them, apparently)
=> Fix "assorted asides" list formatting in dev guide

src/IJulia/setup.jl, src/Interact.jl, test/ijulia.jl
This brings in enough updates to ensure that the unit tests pass on Julia v0.6-dev. I'm still having issues with actually *using* Interact in v0.6, but I think this is at least a step in the right direction. 
With this update, I can execute an `@manipulate` cell in a notebook without errors, but the output of the cell does not update as I move the slider. I don't understand enough about the way IJulia actually works to be able to fix that yet. 
One other note: this converts the nested functions in `IJulia/setup.jl` to anonymous closures to avoid world-age problems. That will hurt performance on Julia v0.4, so if you do go with this method, it might be worth bumping the julia requirement to v0.5 for these changes.
=> fix tests on julia v0.6-dev

.travis.yml, src/manipulate.jl, test/runtests.jl
`@manipulate` was escaping too many things, which meant that it relied on the user having done `using Interact` and `using Reactive`. This change removes that requirement, and will also prevent weird errors in the case that a user has some local function called `signal` or `preserve`. 
Fixes #184 
Also fixes #156
=> fix @manipulate hygiene and add a test

src/IJulia/setup.jl, src/IJulia/setup_old.jl
fixes #186 by wrapping the `setup.jl` code in a module. This is necessary because when Interact does:
```
function __init__()
include("setup.jl")
end
```
`setup.jl` is executed in the user's current workspace, not inside the Interact module, which causes clashes with user-defined functions.
@JobJob can you verify that this fixes the issue for you? 
I think an alternative to this would be to do `eval(Interact, parse(<text of setup.jl>))` which might be even better, but I haven't tried that yet.
=> isolate the IJulia setup inside a module

deps/build.jl
I modified build.jl to use ENV["PYTHON"] on Windows when defined.
=> Make building work for Windows when ENV["PYTHON"] exists

deps/build.jl
This PR tries harder to correctly configure Interact on Windows.
On Windows, running `jupyter` subcommands can be tricky because of JuliaLang/IJulia.jl#363.   I had to reproduce some of the logic from the IJulia build script here.
Also, it tries a bit harder on Windows to find `python.exe`, especially for Conda builds.
This also fixes the issue with `@PYTHON_str` mentioned in #205.
=> try harder to find Jupyter and Python during build

src/IJulia/setup.jl, src/IJulia/statedict.jl, src/widgets.jl
This minor update adds the kwarg continuous_update=Bool (true by default) to the option widgets. 
My motivation for this was to allow non-continuous updates of selection_sliders.
=> Add continuous_update keyword for option widgets and fix a bunch of ipywidget 7 related bugs.

.gitignore, deps/build.jl, src/Interact.jl
Bonuses:
1. run jupyter nbextension install command as well as enable on `Pkg.build("Interact")`
1. report which protocol version (old or new) is used on `using Interact`
1. allow setting protocol version using ENV["WIDGETS_VERSION"]
=> Check for widgetsnbextension version instead of ipywidgets version

src/IJulia/setup.jl, src/IJulia/setup_old.jl, src/widgets.jl
Fixes Progress meter for nbwidgetsextension version >= 3.0.0
Moved progress meter update! method to the correct location. 
Changed its value's type from Int->Float64
```
using Interact
pbar = progress(range=-5.0:0.1:5.0)
display(pbar);
```
```
update!(pbar,-3.3)
```
=> Progress meter fixes

src/widgets.jl
Fix bug wherein option widgets cannot handle certain input. Closes #213 
This revision was successfully tested on
```julia
using Interact
sliders = [
selection_slider(["foo"=> false, "bar"=>true]), 
selection_slider(["foo"=> 1, "bar"=>1.0, "baz"=>"hello"]), 
selection_slider(Dict("foo"=> 1, "bar"=>1.0, "baz"=>"hello")), 
selection_slider([1,2,3]), 
selection_slider([1,"hello",:x, [1,2]]), 
selection_slider(1:10), 
selection_slider([("foo", false), ("bar", true)]), 
selection_slider(2.^(1:0.01:10), label="exponential value"; orientation="vertical"),
selection(enumerate(["fred",2,1 + 0.5im, 0.3]) |> collect, multi=true), 
selection([("a",1), ("b",2), ("c",3)]; multi=true),
]
display.(sliders)
map((x...)->display(x), signal.(sliders)...)
```
I have not been able to test on anything but …
=> Fix type inference of option dict. Closes #213.

.travis.yml, test/REQUIRE, test/runtests.jl
Adds lots of test dependencies, but now you're sure that the notebooks will run without error. NBInclude itself is a lightweight package, the other packages are just needed to run the notebooks.
I wanted to do the notebook in `test/notebooks` as well, but it currently doesn't run on my machine due to a call to some nonstandard `flatten` method.
Note that you can skip certain cells by adding `#NBSKIP` to the cell. This can e.g. be useful to eliminate test dependencies that you really only need for one cell.
Another option would be to skip `03-Interactive Diagrams and Plots.ipynb` completely, to get rid of the Gadfly and PyPlot dependencies.
=> Use NBInclude to test notebooks.

src/Interact.jl
As a user, I don't really care which nbwidgetsextension protocol is being used as long as things are working. In my opinion, printing this message every time I use Interact is just noise.
=> Remove nbwidgetsextension info message

REQUIRE
The new tag of the Interact* set of packages was just merged in METADATA and this ensures that Interact gets the fully featured version (InteractBase 0.2 was still missing some features)
=> bump interactbase deps

README.md, doc/notebooks/01-Introduction.ipynb, doc/notebooks/02-Widgets Overview.ipynb, doc/notebooks/03-Interactive Diagrams and Plots.ipynb, doc/notebooks/04-Animations.ipynb, doc/notebooks/tutorial.ipynb, docs/make.jl, docs/src/deploying.md, docs/src/index.md, docs/src/layout.md, docs/src/observables.md, docs/src/tutorial.jl, docs/src/widgets.md, src/Interact.jl
This effectively turns Interact into a metapackage reexporting most of JuliaGizmos. The main advantages are:
- The user only needs `using Interact` without worrying about how things are internally organized (meaning, where are `Observables` defined or where does `hbox` come from)
- Documentation can be unified here
=> Reexport JuliaGizmos packages and unify docs

doc/notebooks/02-Widgets Overview.ipynb
`e` -> `ℯ` 
Using `e` results in
```
UndefVarError: e not defined
Stacktrace:
[1] top-level scope at In[17]:1
```
=> Use Euler's constant symbol

.github/workflows/CompatHelper.yml, Project.toml
This reforms the compat section to be more explicit with an upper bound. The registry has added an upper bound to prior versions of this package:
https://github.com/JuliaRegistries/General/blob/60bdb5a38cb0be44a4c110129fd57fc3e4f81938/I/Interact/Compat.toml#L31
The upper bound now needs updating.
This also adds CompatHelper. Please follow the instructions at https://juliaregistries.github.io/CompatHelper.jl/dev/ to complete the process.
=> Reform compat section, add CompatHelper
